### ISSUE TITLE
Screens not starting

### ISSUE THREAD

**Issue by Enjoyinbreaks** [lordofwizard/mcserver#11]
There is an issue that happens to me and my second account. Whenever I make a server using your instructions, it shows that server has installed or whatever. But when I do [screen -ls], It says that there are no screens. This means that playit and server haven't started. Also, the server files have not been generated except the .jar file and EULA. PLS HELP!!!!!!!

**Comment by lordofwizard** [comment]
Well i guess it should work. can you come to discord and i will take the tmate access personally to your problem. I think it's the problem occuring with your google cloud machine.

**Comment by Enjoyinbreaks** [comment]
Ok, There's also a similar issue with someone else. SO I don't think it's my google cloud machine specific.
Thanks

**Comment by Enjoyinbreaks** [comment]
Duplicate of #12

**Comment by lordofwizard** [comment]
it's now fixed
