### ISSUE TITLE
Fabric server jar is not used

### ISSUE THREAD

**Issue by Enjoyinbreaks** [lordofwizard/mcserver#13]
Hi i am enjoyinbreaks with an issue again!!!!!

The fabric server jar is added but it is not used. The vanilla jar is used only.

i fixed it by changing the server.jar to fabric-server-launcher.jar in startjavaserver file.

I hope you can fix it in the project.
Thanks

**Comment by lordofwizard** [comment]
Yeah okay it's a simple issue. it will be fixed.
