### ISSUE TITLE
Failed to Establish (Playit)

### ISSUE THREAD

**Issue by GeoXTen** [lordofwizard/mcserver#27]
when trying connect i could'nt connect in and get this issue
![image](https://user-images.githubusercontent.com/46945867/136161920-0b66af76-582c-40c8-8b73-3be6a8d8d356.png)
![image](https://user-images.githubusercontent.com/46945867/136163295-1ae9a61c-97ac-42a5-aa7f-f4b3dad0547a.png)

**Comment by Silent-Crafter** [comment]
playit having issues also join the discord for quick help. https://discord.gg/3qVpM3VPwY
