### ISSUE TITLE
Permission Denied error.

### ISSUE THREAD

**Issue by Cfrolich13** [lordofwizard/mcserver#32]
When trying to clone this repository in the Google Cloud Shell, I get the following error:
fatal: could not create work tree dir 'mcserver': Permission denied

Is there a fix for this?

**Comment by Silent-Crafter** [comment]
you are a 100% not in home directory. just type cd and press enter. you will be in the home directory(the ~ icon). then you can clone it

**Comment by Cfrolich13** [comment]
Thanks. I can’t believe that was the issue I was having. I feel like an idiot now.
