### ISSUE TITLE
Issue when starting the server

### ISSUE THREAD

**Issue by TicTecOfficial** [lordofwizard/mcserver#42]
My server starts up and is fine after being checked. But when I try to get to server console, it says "There is no screen to be resumed matching server". And when I check the files, there is only the basic stuff. Such as the libraries folder, minecraft_1.12.2.jar and stuff like that.

P.S. ignore the name of the cloud shell
![image](https://user-images.githubusercontent.com/97348600/148647735-9ca74a4b-1128-42ff-82df-42498d74b324.png)
![image](https://user-images.githubusercontent.com/97348600/148647740-4d779da3-b79b-42fd-917d-1c74431e52d8.png)

**Comment by Silent-Crafter** [comment]
try renaming the `minecraft_server.1.12.2.jar` to `server.jar`

**Comment by sudoxyz** [comment]
no run sudo screen -r server

**Comment by lordofwizard** [comment]
@TicTecOfficial I am pretty sure you haven't changed the java version to your appropriate version.. also please if possible send us that installer.jar.log

**Comment by Silent-Crafter** [comment]
> no run sudo screen -r server

@sudoxyz  Never run that as sudo

**Comment by Patrick-1-1-1-PH** [comment]
try `chmod +x *`
make sure you are in the server directory where all executables are located

**Comment by TicTecOfficial** [comment]
> @TicTecOfficial I am pretty sure you haven't changed the java version to your appropriate version.. also please if possible send us that installer.jar.log

I'm using Java 8 which from what I heard, is the correct version for a Minecraft 1.12.2 server.

**Comment by Powerful845tiger** [comment]
> try renaming the `minecraft_server.1.12.2.jar` to `server.jar`

That particular file is not meant to be renamed.

> > @TicTecOfficial I am pretty sure you haven't changed the java version to your appropriate version.. also please if possible send us that installer.jar.log
> 
> I'm using Java 8 which from what I heard, is the correct version for a Minecraft 1.12.2 server.

Can you share the installer.jar.log

**Comment by Silent-Crafter** [comment]
> > try renaming the `minecraft_server.1.12.2.jar` to `server.jar`
> 
> That particular file is not meant to be renamed.
> 
> > > @TicTecOfficial I am pretty sure you haven't changed the java version to your appropriate version.. also please if possible send us that installer.jar.log
> > 
> > 
> > I'm using Java 8 which from what I heard, is the correct version for a Minecraft 1.12.2 server.
> 
> Can you share the installer.jar.log as lordofwizard mentioned

sorry for being rude but i know 100x better than you of this project dumb guy and that particular file is necessary to be renamed. the startJavaServer script launches `java -jar server.jar` with the arguments like -Xmx. that file is our main server.jar file which didn't got renamed automatically.

Also this issue is like month old and the author isn't even cooperating why is this even open

**Comment by Powerful845tiger** [comment]
![image](https://user-images.githubusercontent.com/73754602/155674661-a8100fb2-cb7a-485b-8f3c-c3fd25611987.png)
sorry for being rude but  minecraft_server.1.12.2.jar is not meant to be renamed dumb guy. As shown in the screenshot I tried installing forge 1.12.2 and those files where generated in which minecraft_server.1.12.2.jar  was not renamed.
