### ISSUE TITLE
Updating to new playit version causes issues

### ISSUE THREAD

**Issue by Enjoyinbreaks** [lordofwizard/mcserver#46]
updating to new playit version causes issues and cant connect

**Comment by YongSheng109** [comment]
then don't update btw ig startafk don't work right?

**Comment by lordofwizard** [comment]
The playit new version works.. tut for it will be uploaded soon... It requires a open tcp tunnel and a playit.gg account..

**Comment by Enjoyinbreaks** [comment]
figured it out. Thanks
