### ISSUE TITLE
BADROCK SERVER

### ISSUE THREAD

**Issue by Bimaadhinirma** [lordofwizard/mcserver#47]
in badrock server i dont see playit how to fix it, if dont have playit i cant playing server with my friends

**Comment by SkyNinja6T9** [comment]
Same , in bedrock it didn't detect playit.gg , how to fix that ?

**Comment by Primeplayer7870** [comment]
Hey, I found the fix. Just run
>curl -SsL https://playit-cloud.github.io/ppa/key.gpg | sudo apt-key add -
>sudo curl -SsL -o /etc/apt/sources.list.d/playit-cloud.list https://playit-cloud.github.io/ppa/playit-cloud.list
>sudo apt update
>sudo apt install playit
Found it in the installjava file
