### ISSUE TITLE
Stuck  on - AgentConfigUpdated     1                                                                                                                                   ┃ ┃                                  

### ISSUE THREAD

**Issue by zainullahk** [lordofwizard/mcserver#50]
i ran screen -r playit and it is stuck on agentconfig updated 1

**Comment by zainullahk** [comment]
i reset config of playit and it keeps doing this over and over again

**Comment by zainullahk** [comment]
┃4 - NewClientSetupFailed { client_id: 2 }                                                                                                                     ┃
┃3 - ClientAccepted { client_id: 2, proto: Tcp, tunnel_addr: 147.185.221.223:60803, peer_addr: 176.205.19.143:3551, host_addr: 127.0.0.1:25565 }               ┃
┃2 - NewClientSetupFailed { client_id: 1 }                                                                                                                     ┃
┃1 - ClientAccepted { client_id: 1, proto: Tcp, tunnel_addr: 147.185.221.223:60803, peer_addr: 176.205.19.143:3547, host_addr: 127.0.0.1:25565 }

**Comment by zainullahk** [comment]
i checked ip on playit itwont let me join

**Comment by Enjoyinbreaks** [comment]
Hello,

Please try the latest version and then tell us

NO thanks
Enjoyinbreaks
