### ISSUE TITLE
The script is not able to detect tunnels from playit.gg

### ISSUE THREAD

**Issue by Xandarcage1290** [lordofwizard/mcserver#57]
it says "No tunnels found, Getting an error trying to load tunnels...." 

![Screenshot from 2023-01-14 19-29-57](https://user-images.githubusercontent.com/91640548/212475715-d18f1e9f-6dad-4370-be02-c453228c2fd7.png)

**Comment by maxomatic458** [comment]
thats happening because the older playit versions are discontinued
#56 fixes that

**Comment by Xandarcage1290** [comment]
hi so I solved this issue by updating the playit thing like you told (thank you btw) but now im having another issue with forge now. It just keeps crashing. here's crash log
![image](https://user-images.githubusercontent.com/91640548/215342910-2d3f9d01-4dbe-48c2-bb63-f60bf2d2308f.png)
