### ISSUE TITLE
Playit.gg does not work

### ISSUE THREAD

**Issue by Saketh9033** [lordofwizard/mcserver#59]
When I do `screen -r playit` it says there is no screen to be resumed matching playit.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/118751571/222427638-bea7fd33-ff85-405e-93ab-11953f4096d5.png">

To fix it I need to delete tunnel and create new tunnel and link it again

**Comment by lordofwizard** [comment]
Have you updated the whole mcserver package? because as per my knowledge it is working flawlessly

**Comment by dada123456554** [comment]
@lordofwizard hi there, i have the same issue as Saketh9033, just cannot get away accessing the server, and showed "there is no screen to be resumed playit"  ( i installed the bedrock version)

**Comment by Saketh9033** [comment]
> Have you updated the whole mcserver package? because as per my knowledge it is working flawlessly

Like 2-3 times I deleted all files and installed again still same

**Comment by dada123456554** [comment]
@Saketh9033 same situation as yours, not sure what happen,

**Comment by Saketh9033** [comment]
> Have you updated the whole mcserver package? because as per my knowledge it is working flawlessly

Yes
