### ISSUE TITLE
playit.gg problem, any fixes?

### ISSUE THREAD

**Issue by boatytheboater** [lordofwizard/mcserver#60]
<img width="461" alt="Screenshot 2023-04-20 at 05 21 00" src="https://user-images.githubusercontent.com/119733188/233226387-8d160390-a811-4569-b3be-e8d53f4162be.png">

**Comment by Hello20232010** [comment]
How can I fix it ?

**Comment by boatytheboater** [comment]
> How can I fix it ?

thats what im asking

**Comment by bIaBlaBla** [comment]
after trying to make a bedrock server, it gives the same error, while having nothing on the playit file

**Comment by lordofwizard** [comment]
@bIaBlaBla, Looking to fix it soon.

**Comment by Redhaxx111** [comment]
@bIaBlaBla, can you help me do it?

**Comment by bIaBlaBla** [comment]
> @bIaBlaBla, can you help me do it?
if i remember correctly i deleted the playit somewhere in the folders and installed the linux one from their website there, honestly i'd recommend you to just pay a hosting provider, some can get as low as 1 dollar per gigabyte or less, its very cheap and 1 hour of mcdonalds work will get you a nice server
