### ISSUE TITLE
Server lagging so much without a single player online/1 - 2 players online [Fabric]

### ISSUE THREAD

**Issue by NotFlow69** [lordofwizard/mcserver#62]
i hosted my smp with this tutorial and sometimes the server crashes without a single player online, im using fabric a very, VERY low amount of mods, i have edited the startup file for ram and so on but the server is lagging so much that aternos is better, PLEASE HELP ME!!!! @lordofwizard @DumbCaveSpider

**Comment by lordofwizard** [comment]
@NotFlow69 Can you attach a few logs to go along with it?
