### ISSUE TITLE
playit screen is missing after restarting server

### ISSUE THREAD

**Issue by whybirdslie** [lordofwizard/mcserver#75]
After some time needing to restart the server, the playit.gg screen does not automaticall open up.

when trying to execute startPlayIt the following Error shows: line 5: playit: command not found

![image](https://github.com/lordofwizard/mcserver/assets/163842114/d90a3327-3cc9-4b73-ab32-293fb8c58882)

**Comment by lordofwizard** [comment]
I am sure the binary release if out from playit.gg website. 
Working on a new rust based release. Thanks for reporting 👍

**Comment by congchuahiep** [comment]
![image](https://github.com/lordofwizard/mcserver/assets/69245481/b1d7f756-86ff-4d4e-a9a1-b6967c32bed2)
same thing here, any solution yet?

**Comment by congchuahiep** [comment]
I find solution, you need to reinstall playit for every restart cloud shell. Just paste it in terminal
```
curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
sudo apt update
sudo apt install playit
```
When it's done, restart server and everything should be fine
