### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by legendaryhero13** [lordofwizard/mcserver#87]
This is what comes up at the crash log, I do not know what to make out of it:

Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
	java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
./startBedrockServer: line 3: ./bedrock_server: No such file or directory

**Comment by lordofwizard** [comment]
working on fixing it in the new release.
